# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.8.2'

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interviews_interventions.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    1   -1   -1    4    2    3    2    0  180 1500]
 [  85    3    1    0    2    1    3    1   34  150 1685]
 [  80    6   -2   -1    3    1    3    1   34  120 1670]
 [  80    6   -2   -2    2    1    2    1  119   90 1215]
 [  65    5   -2   -1    3    1    1    1    0   90 1595]
 [  90    2    0   -1    1    1    1    2   15   90   45]
 [  90    6   -2   -2    1    1    1    1    0   90 1400]
 [  85    2   -1   -1    1    3    1    1    0   90 1530]
 [  80    2   -1   -1    1    3    1    1    0   90 1170]
 [  85    3   -1   -1    1    2    1    1   12  120 1430]
 [  80    6   -2   -2    1    2    3    1   11    0 1245]
 [  80    3   -1   -1    2    2    4    2    0  180 1585]]


In [ ]:
print(y)

['N' 'N' 'N' 'N' 'D' 'D' 'N' 'N' 'M' 'M' 'M' 'N' 'N' 'N']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.83205029 -0.27196415 -0.46563307 -0.34836651 -0.91287093 -0.11470787
  -1.2094158  -0.82495791 -0.3492545   0.05423261  0.18180811]
 [-0.69337525 -1.46860639 -0.46563307 -0.34836651  2.09960314 -0.11470787
   0.69109474  0.47140452 -0.71225917  1.24735013  0.33649568]
 [-0.69337525 -0.27196415 -0.46563307 -0.34836651  0.09128709 -0.11470787
   1.64135001  0.47140452 -0.71225917  1.24735013  0.52433059]
 [ 0.83205029 -0.87028527 -0.46563307 -0.34836651 -0.91287093  1.14707867
  -1.2094158  -0.82495791 -0.71225917 -0.54232614  0.40279035]
 [-0.69337525  0.9246781   1.72949427  1.95085244  1.09544512  1.14707867
   0.69109474  1.76776695  0.31625407  0.65079137  0.80055838]
 [ 2.35747583 -0.87028527  0.26607604 -0.34836651 -0.91287093 -1.3764944
  -1.2094158   0.47140452 -0.25850333 -0.54232614 -2.8787959 ]
 [-0.69337525 -0.87028527 -0.46563307 -0.34836651 -0.91287093  1.14707867
  -1.2094158  -0.82495791 -0.71225917 -0.54232614 -0.39274571]
 [ 0.83205029 -0.27196415  0.99778516  0.4

In [ ]:
print(y_train)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:

ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='relu'))


### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
3/3 [==============================] - 2s 12ms/step - loss: 1.1297 - accuracy: 0.0909
Epoch 2/200
3/3 [==============================] - 0s 10ms/step - loss: 1.0852 - accuracy: 0.3636
Epoch 3/200
3/3 [==============================] - 0s 7ms/step - loss: 1.0733 - accuracy: 0.5455
Epoch 4/200
3/3 [==============================] - 0s 9ms/step - loss: 1.0598 - accuracy: 0.8182
Epoch 5/200
3/3 [==============================] - 0s 16ms/step - loss: 1.0455 - accuracy: 0.7273
Epoch 6/200
3/3 [==============================] - 0s 5ms/step - loss: 1.0282 - accuracy: 0.7273
Epoch 7/200
3/3 [==============================] - 0s 8ms/step - loss: 1.0112 - accuracy: 0.7273
Epoch 8/200
3/3 [==============================] - 0s 9ms/step - loss: 0.9937 - accuracy: 0.7273
Epoch 9/200
3/3 [==============================] - 0s 8ms/step - loss: 0.9741 - accuracy: 0.7273
Epoch 10/200
3/3 [==============================] - 0s 7ms/step - loss: 0.9550 - accuracy: 0.7273
Epoch 11/200
3/3 [========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

In [ ]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])



In [ ]:
round(ytest_pred,y_test_predRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.3333333333333333

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='micro')

0.3333333333333333

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_predRounded, average='micro')

0.3333333333333333

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test,  y_test_predRounded, average='micro')

0.3333333333333333