# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [2]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('ymrs_hdrs.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0 1 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 2 1 0 0 0 0 2 0 1 1 0 0 0]
 [0 0 2 0 2 1 0 1 0 0 0 0 0 1 0 0 0 0]
 [1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 2 0 0 1 1 0 0 0 0 0]
 [0 0 2 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 1 0 2]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [5]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'N' 'M' 'N' 'D' 'D' 'M' 'N'
 'M' 'D' 'N' 'N' 'N' 'D' 'D']


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
y= np.array(y.reshape(len(y),1))

In [7]:
#print(y)

One Hot Encoding the Y column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [9]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train

array([[0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0])

(20, 18)
(18,)
[0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 1 0 2]


### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1               # each feature is represented by 1 number

X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [15]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

### Initializing the ANN

In [16]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 100)

Epoch 1/100
4/4 [==============================] - 2s 6ms/step - loss: 1.1026 - accuracy: 0.4500
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 1.0500 - accuracy: 0.5500
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0106 - accuracy: 0.6000
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9741 - accuracy: 0.6000
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9128 - accuracy: 0.6500
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.8674 - accuracy: 0.7000
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8138 - accuracy: 0.7000
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7501 - accuracy: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6870 - accuracy: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6218 - accuracy: 0.7500
Epoch 11/100
4/4 [===========

### Training the ANN on the Training set

In [18]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)


1/1 [==============================] - 0s 216ms/step - loss: 2.0245 - accuracy: 0.6000


[2.024498462677002, 0.6000000238418579]

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [19]:
y_pred = model.predict(X_test_reshaped)

1/1 [==============================] - 0s 146ms/step


In [20]:
y_pred

array([[9.9963892e-01, 3.4477039e-11, 3.6104649e-04],
       [1.1860121e-05, 9.9809068e-01, 1.8973986e-03],
       [9.9967253e-01, 1.6840971e-07, 3.2736946e-04],
       [5.7628341e-03, 5.5015528e-01, 4.4408184e-01],
       [7.9733390e-01, 2.0668496e-07, 2.0266590e-01]], dtype=float32)

In [21]:
y_predRounded= []
y_predEncoded = []


In [22]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [23]:
round(y_pred,y_predRounded)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predRounded)

0.6

In [25]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predRounded, average='micro')

0.6