# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [5]:
tf.__version__

'2.8.2'

### Importing the dataset

In [6]:
dataset = pd.read_csv('ymrs_hdrs.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[0 1 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 2 1 0 0 0 0 2 0 1 1 0 0 0]
 [0 0 2 0 2 1 0 1 0 0 0 0 0 1 0 0 0 0]
 [1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 2 0 0 1 1 0 0 0 0 0]
 [0 0 2 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 2 0 0 0 1 0 2]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [8]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'N' 'M' 'N' 'D' 'D' 'M' 'N'
 'M' 'D' 'N' 'N' 'N' 'D' 'D']


### Encoding categorical data

In [9]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [11]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[-0.33333333 -0.42008403  2.          0.         -0.33333333 -0.60302269
  -0.31448545 -0.31448545 -0.31448545 -0.22941573 -0.33333333  1.52752523
  -0.22941573 -0.22941573 -0.22941573  4.35889894  0.          4.35889894]
 [-0.33333333 -0.42008403 -0.5         0.         -0.33333333 -0.60302269
  -0.31448545 -0.31448545 -0.31448545 -0.22941573 -0.33333333 -0.65465367
  -0.22941573 -0.22941573 -0.22941573 -0.22941573  0.         -0.22941573]
 [-0.33333333 -0.42008403 -0.5         0.         -0.33333333 -0.60302269
  -0.31448545 -0.31448545 -0.31448545 -0.22941573 -0.33333333 -0.65465367
  -0.22941573 -0.22941573 -0.22941573 -0.22941573  0.         -0.22941573]
 [-0.33333333 -0.42008403 -0.5         0.         -0.33333333 -0.60302269
  -0.31448545 -0.31448545 -0.31448545 -0.22941573  3.         -0.65465367
  -0.22941573 -0.22941573 -0.22941573 -0.22941573  0.         -0.22941573]
 [-0.33333333 -0.42008403 -0.5         0.         -0.33333333  0.90453403
  -0.31448545 -0.31448545 -0.31448

In [15]:
print(y_train)

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [16]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [17]:

ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='relu'))


### Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 100)

Epoch 1/100
4/4 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.2500
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0719 - accuracy: 0.3500
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0561 - accuracy: 0.3500
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0426 - accuracy: 0.3500
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0347 - accuracy: 0.3000
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0221 - accuracy: 0.3000
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0093 - accuracy: 0.3500
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9872 - accuracy: 0.4000
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9621 - accuracy: 0.4000
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9340 - accuracy: 0.4000
Epoch 11/100
4/4 [===========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [22]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

In [23]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [24]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])

  

In [25]:
round(ytest_pred,y_test_predRounded)

In [26]:
print(classification_report(y_test_predRounded,y_test))


              precision    recall  f1-score   support

           0       1.00      0.33      0.50         3
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

   micro avg       0.40      0.40      0.40         5
   macro avg       0.50      0.44      0.39         5
weighted avg       0.70      0.40      0.43         5
 samples avg       0.40      0.40      0.40         5



In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.4

In [28]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='micro')

0.4000000000000001

In [29]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_predRounded, average='micro')

0.4

In [30]:
from sklearn.metrics import precision_score
precision_score(y_test,  y_test_predRounded, average='micro')

0.4