# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interventions_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[80  5]
 [80  5]
 [80  1]
 [60  3]
 [70  5]
 [80  3]
 [85  2]
 [80  3]
 [90  3]
 [85  3]
 [75  4]
 [75  4]
 [90  5]
 [90  3]
 [80  6]
 [50  7]
 [80  6]
 [60  5]
 [85  2]
 [75  5]
 [85  1]
 [65  5]
 [85  5]
 [90  2]
 [70  5]
 [90  3]
 [70  5]
 [80  5]
 [70  2]
 [85  2]
 [95  2]
 [95  2]
 [95  4]
 [95  4]
 [85  2]
 [90  6]
 [90  3]
 [75  4]
 [70  5]
 [70  5]
 [85  2]
 [80  2]
 [90  3]
 [80  3]
 [90  2]
 [85  3]
 [90  4]
 [80  6]
 [95  2]
 [85  3]
 [85  3]
 [85  3]
 [85  6]
 [90  3]
 [80  6]
 [90  3]
 [90  4]
 [80  3]
 [90  4]]


In [ ]:
print(y)

['N' 'N' 'N' 'M' 'N' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'D' 'D' 'D' 'D'
 'N' 'D' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'M'
 'D' 'M' 'D' 'D' 'M' 'M' 'N' 'M' 'N' 'D' 'N' 'M' 'D' 'D' 'N' 'N' 'N' 'D'
 'N' 'D' 'D' 'N' 'N']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

In [ ]:
#print(y)

One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[95,  2],
       [80,  2],
       [95,  4],
       [90,  3],
       [95,  2],
       [80,  3],
       [80,  6],
       [95,  4],
       [85,  3],
       [85,  2],
       [75,  4],
       [90,  4],
       [85,  2],
       [90,  3],
       [80,  5],
       [50,  7],
       [80,  3],
       [95,  2],
       [80,  6],
       [85,  3],
       [85,  1],
       [85,  3],
       [90,  3],
       [90,  3],
       [90,  3],
       [60,  5],
       [90,  4],
       [80,  3],
       [85,  6],
       [70,  5],
       [80,  5],
       [90,  5],
       [85,  3],
       [70,  5],
       [85,  2],
       [90,  2],
       [90,  3],
       [65,  5],
       [75,  5],
       [85,  3],
       [70,  5],
       [80,  6],
       [60,  3],
       [80,  5],
       [90,  3],
       [80,  6],
       [90,  2]])

In [ ]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0])

(47, 2)
(2,)
[95  2]


### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1               # each feature is represented by 1 number

X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [ ]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

### Initializing the ANN

In [ ]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=1, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=1, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=1, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
10/10 [==============================] - 2s 3ms/step - loss: 1.0812 - accuracy: 0.5319
Epoch 2/200
10/10 [==============================] - 0s 3ms/step - loss: 1.0353 - accuracy: 0.5319
Epoch 3/200
10/10 [==============================] - 0s 3ms/step - loss: 1.0036 - accuracy: 0.5319
Epoch 4/200
10/10 [==============================] - 0s 4ms/step - loss: 0.9761 - accuracy: 0.5319
Epoch 5/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9570 - accuracy: 0.5319
Epoch 6/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9546 - accuracy: 0.5319
Epoch 7/200
10/10 [==============================] - 0s 4ms/step - loss: 0.9442 - accuracy: 0.5319
Epoch 8/200
10/10 [==============================] - 0s 4ms/step - loss: 0.9370 - accuracy: 0.5319
Epoch 9/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9364 - accuracy: 0.5319
Epoch 10/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9273 - accuracy: 0.5319
Epoch 11/

### Training the ANN on the Training set

In [ ]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)


3/3 [==============================] - 0s 7ms/step - loss: 1.7846 - accuracy: 0.3333


[1.7845877408981323, 0.3333333432674408]

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_pred = model.predict(X_test_reshaped)

1/1 [==============================] - 0s 217ms/step


In [ ]:
y_pred

array([[5.4285419e-01, 1.7716376e-03, 4.5537412e-01],
       [1.5532444e-01, 3.9372221e-02, 8.0530328e-01],
       [6.0151690e-03, 3.4550473e-01, 6.4848018e-01],
       [3.0971455e-06, 9.7895789e-01, 2.1038940e-02],
       [6.4139185e-04, 7.1458155e-01, 2.8477705e-01],
       [4.4567873e-08, 9.9423337e-01, 5.7665361e-03],
       [1.3157094e-03, 3.5569236e-01, 6.4299196e-01],
       [1.5336791e-01, 1.6593708e-02, 8.3003837e-01],
       [1.3157094e-03, 3.5569236e-01, 6.4299196e-01],
       [1.4412822e-01, 1.8643860e-02, 8.3722794e-01],
       [5.4285425e-01, 1.7716377e-03, 4.5537418e-01],
       [6.4139179e-04, 7.1458155e-01, 2.8477705e-01]], dtype=float32)

In [ ]:
y_predRounded= []
y_predEncoded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [ ]:
round(y_pred,y_predRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predRounded)

0.3333333333333333

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predRounded, average='micro')

0.3333333333333333