# Artificial Neural Network

### Importing the libraries

In [ ]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interventions_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[80  5]
 [80  5]
 [80  1]
 [60  3]
 [70  5]
 [80  3]
 [85  2]
 [80  3]
 [90  3]
 [85  3]
 [75  4]
 [75  4]
 [90  5]
 [90  3]
 [80  6]
 [50  7]
 [80  6]
 [60  5]
 [85  2]
 [75  5]
 [85  1]
 [65  5]
 [85  5]
 [90  2]
 [70  5]
 [90  3]
 [70  5]
 [80  5]
 [70  2]
 [85  2]
 [95  2]
 [95  2]
 [95  4]
 [95  4]
 [85  2]
 [90  6]
 [90  3]
 [75  4]
 [70  5]
 [70  5]
 [85  2]
 [80  2]
 [90  3]
 [80  3]
 [90  2]
 [85  3]
 [90  4]
 [80  6]
 [95  2]
 [85  3]
 [85  3]
 [85  3]
 [85  6]
 [90  3]
 [80  6]
 [90  3]
 [90  4]
 [80  3]
 [90  4]]


In [ ]:
print(y)

['N' 'N' 'N' 'M' 'N' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'D' 'D' 'D' 'D'
 'N' 'D' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'M'
 'D' 'M' 'D' 'D' 'M' 'M' 'N' 'M' 'N' 'D' 'N' 'M' 'D' 'D' 'N' 'N' 'N' 'D'
 'N' 'D' 'D' 'N' 'N']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

In [ ]:
print(y)

[['N']
 ['N']
 ['N']
 ['M']
 ['N']
 ['M']
 ['N']
 ['N']
 ['M']
 ['N']
 ['N']
 ['N']
 ['N']
 ['N']
 ['D']
 ['D']
 ['D']
 ['D']
 ['N']
 ['D']
 ['N']
 ['N']
 ['N']
 ['N']
 ['D']
 ['N']
 ['D']
 ['N']
 ['M']
 ['M']
 ['N']
 ['N']
 ['N']
 ['N']
 ['D']
 ['M']
 ['D']
 ['M']
 ['D']
 ['D']
 ['M']
 ['M']
 ['N']
 ['M']
 ['N']
 ['D']
 ['N']
 ['M']
 ['D']
 ['D']
 ['N']
 ['N']
 ['N']
 ['D']
 ['N']
 ['D']
 ['D']
 ['N']
 ['N']]


One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[95,  2],
       [80,  2],
       [95,  4],
       [90,  3],
       [95,  2],
       [80,  3],
       [80,  6],
       [95,  4],
       [85,  3],
       [85,  2],
       [75,  4],
       [90,  4],
       [85,  2],
       [90,  3],
       [80,  5],
       [50,  7],
       [80,  3],
       [95,  2],
       [80,  6],
       [85,  3],
       [85,  1],
       [85,  3],
       [90,  3],
       [90,  3],
       [90,  3],
       [60,  5],
       [90,  4],
       [80,  3],
       [85,  6],
       [70,  5],
       [80,  5],
       [90,  5],
       [85,  3],
       [70,  5],
       [85,  2],
       [90,  2],
       [90,  3],
       [65,  5],
       [75,  5],
       [85,  3],
       [70,  5],
       [80,  6],
       [60,  3],
       [80,  5],
       [90,  3],
       [80,  6],
       [90,  2]])

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 1.26591947 -1.19203991]
 [-0.25967579 -1.19203991]
 [ 1.26591947  0.20860698]
 [ 0.75738771 -0.49171646]
 [ 1.26591947 -1.19203991]
 [-0.25967579 -0.49171646]
 [-0.25967579  1.60925388]
 [ 1.26591947  0.20860698]
 [ 0.24885596 -0.49171646]
 [ 0.24885596 -1.19203991]
 [-0.76820754  0.20860698]
 [ 0.75738771  0.20860698]
 [ 0.24885596 -1.19203991]
 [ 0.75738771 -0.49171646]
 [-0.25967579  0.90893043]
 [-3.3108663   2.30957733]
 [-0.25967579 -0.49171646]
 [ 1.26591947 -1.19203991]
 [-0.25967579  1.60925388]
 [ 0.24885596 -0.49171646]
 [ 0.24885596 -1.89236336]
 [ 0.24885596 -0.49171646]
 [ 0.75738771 -0.49171646]
 [ 0.75738771 -0.49171646]
 [ 0.75738771 -0.49171646]
 [-2.29380279  0.90893043]
 [ 0.75738771  0.20860698]
 [-0.25967579 -0.49171646]
 [ 0.24885596  1.60925388]
 [-1.27673929  0.90893043]
 [-0.25967579  0.90893043]
 [ 0.75738771  0.90893043]
 [ 0.24885596 -0.49171646]
 [-1.27673929  0.90893043]
 [ 0.24885596 -1.19203991]
 [ 0.75738771 -1.19203991]
 [ 0.75738771 -0.49171646]
 

In [ ]:
y_train

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Part 2 - Building the MLP

### Initializing the MLP

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(81,27,9,3),activation="relu",solver='adam', random_state=1)

## Part 3 - Training the MLP

### Training the MLP on the Training set

In [ ]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(81, 27, 9, 3), random_state=1)

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
y_test_pred=clf.predict(X_test)

In [ ]:
print(clf.score(X_test, y_test))


0.3333333333333333


In [ ]:
print(classification_report(y_test,y_test_pred))



              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       1.00      0.25      0.40         4
           2       0.38      0.50      0.43         6

   micro avg       0.45      0.42      0.43        12
   macro avg       0.62      0.42      0.44        12
weighted avg       0.60      0.42      0.43        12
 samples avg       0.38      0.42      0.39        12



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_test_pred

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0]])