# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.8.2'

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interventions_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[80  5]
 [80  5]
 [80  1]
 [60  3]
 [70  5]
 [80  3]
 [85  2]
 [80  3]
 [90  3]
 [85  3]
 [75  4]
 [75  4]
 [90  5]
 [90  3]
 [80  6]
 [50  7]
 [80  6]
 [60  5]
 [85  2]
 [75  5]
 [85  1]
 [65  5]
 [85  5]
 [90  2]
 [70  5]
 [90  3]
 [70  5]
 [80  5]
 [70  2]
 [85  2]
 [95  2]
 [95  2]
 [95  4]
 [95  4]
 [85  2]
 [90  6]
 [90  3]
 [75  4]
 [70  5]
 [70  5]
 [85  2]
 [80  2]
 [90  3]
 [80  3]
 [90  2]
 [85  3]
 [90  4]
 [80  6]
 [95  2]
 [85  3]
 [85  3]
 [85  3]
 [85  6]
 [90  3]
 [80  6]
 [90  3]
 [90  4]
 [80  3]
 [90  4]]


In [ ]:
print(y)

['N' 'N' 'N' 'M' 'N' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'D' 'D' 'D' 'D'
 'N' 'D' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'M'
 'D' 'M' 'D' 'D' 'M' 'M' 'N' 'M' 'N' 'D' 'N' 'M' 'D' 'D' 'N' 'N' 'N' 'D'
 'N' 'D' 'D' 'N' 'N']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 1.26591947 -1.19203991]
 [-0.25967579 -1.19203991]
 [ 1.26591947  0.20860698]
 [ 0.75738771 -0.49171646]
 [ 1.26591947 -1.19203991]
 [-0.25967579 -0.49171646]
 [-0.25967579  1.60925388]
 [ 1.26591947  0.20860698]
 [ 0.24885596 -0.49171646]
 [ 0.24885596 -1.19203991]
 [-0.76820754  0.20860698]
 [ 0.75738771  0.20860698]
 [ 0.24885596 -1.19203991]
 [ 0.75738771 -0.49171646]
 [-0.25967579  0.90893043]
 [-3.3108663   2.30957733]
 [-0.25967579 -0.49171646]
 [ 1.26591947 -1.19203991]
 [-0.25967579  1.60925388]
 [ 0.24885596 -0.49171646]
 [ 0.24885596 -1.89236336]
 [ 0.24885596 -0.49171646]
 [ 0.75738771 -0.49171646]
 [ 0.75738771 -0.49171646]
 [ 0.75738771 -0.49171646]
 [-2.29380279  0.90893043]
 [ 0.75738771  0.20860698]
 [-0.25967579 -0.49171646]
 [ 0.24885596  1.60925388]
 [-1.27673929  0.90893043]
 [-0.25967579  0.90893043]
 [ 0.75738771  0.90893043]
 [ 0.24885596 -0.49171646]
 [-1.27673929  0.90893043]
 [ 0.24885596 -1.19203991]
 [ 0.75738771 -1.19203991]
 [ 0.75738771 -0.49171646]
 

In [ ]:
print(y_train)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:

ann.add(tf.keras.layers.Dense(units=81, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=27, activation='relu'))
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))


### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
10/10 [==============================] - 2s 7ms/step - loss: 1.0456 - accuracy: 0.3404
Epoch 2/200
10/10 [==============================] - 0s 4ms/step - loss: 0.9949 - accuracy: 0.5745
Epoch 3/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9639 - accuracy: 0.5957
Epoch 4/200
10/10 [==============================] - 0s 3ms/step - loss: 0.9298 - accuracy: 0.5957
Epoch 5/200
10/10 [==============================] - 0s 4ms/step - loss: 0.9091 - accuracy: 0.6383
Epoch 6/200
10/10 [==============================] - 0s 3ms/step - loss: 0.8886 - accuracy: 0.6383
Epoch 7/200
10/10 [==============================] - 0s 6ms/step - loss: 0.8745 - accuracy: 0.6383
Epoch 8/200
10/10 [==============================] - 0s 4ms/step - loss: 0.8640 - accuracy: 0.6383
Epoch 9/200
10/10 [==============================] - 0s 3ms/step - loss: 0.8603 - accuracy: 0.6383
Epoch 10/200
10/10 [==============================] - 0s 3ms/step - loss: 0.8528 - accuracy: 0.6383
Epoch 11/

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

In [ ]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])



In [ ]:
round(ytest_pred,y_test_predRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.3333333333333333

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='micro')

0.3333333333333333

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_predRounded, average='micro')

0.3333333333333333

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test,  y_test_predRounded, average='micro')

0.3333333333333333