# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [2]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('hdrs_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 3 0 0 2 3 0 1 3 0 0 0]
 [2 1 0 0 2 0 0 0 0 0 1 0 1 0 2 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 1 0 0 0 0 0 0 0 2 0 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 2 0

In [5]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'D' 'D' 'N' 'N' 'N' 'N' 'N' 'D' 'N'
 'M' 'D' 'N' 'M' 'D' 'D' 'M' 'N' 'N' 'M' 'D' 'N' 'N' 'N' 'N' 'D' 'N' 'D']


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
y= np.array(y.reshape(len(y),1))

In [7]:
#print(y)

One Hot Encoding the Y column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [9]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0])

(28, 20)
(20,)
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1               # each feature is represented by 1 number

X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [15]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

### Initializing the ANN

In [16]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
6/6 [==============================] - 2s 9ms/step - loss: 1.0902 - accuracy: 0.6429
Epoch 2/200
6/6 [==============================] - 0s 5ms/step - loss: 1.0389 - accuracy: 0.7143
Epoch 3/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9905 - accuracy: 0.6429
Epoch 4/200
6/6 [==============================] - 0s 7ms/step - loss: 0.9369 - accuracy: 0.7143
Epoch 5/200
6/6 [==============================] - 0s 5ms/step - loss: 0.8778 - accuracy: 0.7143
Epoch 6/200
6/6 [==============================] - 0s 5ms/step - loss: 0.8071 - accuracy: 0.7143
Epoch 7/200
6/6 [==============================] - 0s 6ms/step - loss: 0.7543 - accuracy: 0.7143
Epoch 8/200
6/6 [==============================] - 0s 5ms/step - loss: 0.7114 - accuracy: 0.7143
Epoch 9/200
6/6 [==============================] - 0s 5ms/step - loss: 0.6586 - accuracy: 0.7500
Epoch 10/200
6/6 [==============================] - 0s 5ms/step - loss: 0.6206 - accuracy: 0.7500
Epoch 11/200
6/6 [===========

### Training the ANN on the Training set

In [18]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)


2/2 [==============================] - 0s 11ms/step - loss: 9.0916 - accuracy: 0.2500


[9.091634750366211, 0.25]

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [19]:
y_pred = model.predict(X_test_reshaped)

1/1 [==============================] - 0s 139ms/step


In [20]:
y_pred

array([[4.6304055e-03, 2.0647360e-06, 9.9536753e-01],
       [7.4575916e-02, 7.5490409e-01, 1.7051999e-01],
       [1.4672475e-08, 2.0986293e-13, 9.9999994e-01],
       [1.8566216e-05, 9.9960524e-01, 3.7617359e-04],
       [1.2277531e-04, 3.2447553e-03, 9.9663246e-01],
       [4.1574065e-05, 2.8444183e-05, 9.9992996e-01],
       [9.2715538e-16, 1.2785400e-17, 9.9999994e-01],
       [1.4168078e-01, 2.4240412e-01, 6.1591506e-01]], dtype=float32)

In [21]:
y_predRounded= []
y_predEncoded = []


In [22]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [23]:
round(y_pred,y_predRounded)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predRounded)

0.25

In [26]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predRounded, average='micro')

0.25