# Artificial Neural Network

### Importing the libraries

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [26]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [27]:
dataset = pd.read_csv('ymrs_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [28]:
print(X)

[[0 1 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [1 1 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 2 0 0]
 [1 0 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 2 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [29]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'N'
 'M' 'D' 'N' 'D' 'M' 'D' 'M' 'N' 'N' 'M' 'D' 'N' 'N' 'N' 'D' 'N' 'D']


### Encoding categorical data

Label Encoding the "Gender" column

In [30]:
y= np.array(y.reshape(len(y),1))

In [31]:
#print(y)

One Hot Encoding the Y column

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [33]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [35]:
X_train

array([[0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 0, 0,

In [36]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0])

(28, 11)
(11,)
[0 1 0 0 0 2 0 0 2 0 0]


### Feature Scaling

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1               # each feature is represented by 1 number

X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [39]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

### Initializing the ANN

In [40]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Compiling the ANN

In [41]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
6/6 [==============================] - 3s 14ms/step - loss: 1.1004 - accuracy: 0.3571
Epoch 2/200
6/6 [==============================] - 0s 8ms/step - loss: 1.0690 - accuracy: 0.5714
Epoch 3/200
6/6 [==============================] - 0s 11ms/step - loss: 1.0403 - accuracy: 0.5000
Epoch 4/200
6/6 [==============================] - 0s 8ms/step - loss: 1.0025 - accuracy: 0.6429
Epoch 5/200
6/6 [==============================] - 0s 7ms/step - loss: 0.9646 - accuracy: 0.5714
Epoch 6/200
6/6 [==============================] - 0s 7ms/step - loss: 0.9054 - accuracy: 0.6071
Epoch 7/200
6/6 [==============================] - 0s 7ms/step - loss: 0.8555 - accuracy: 0.6071
Epoch 8/200
6/6 [==============================] - 0s 7ms/step - loss: 0.8022 - accuracy: 0.6071
Epoch 9/200
6/6 [==============================] - 0s 11ms/step - loss: 0.7621 - accuracy: 0.6071
Epoch 10/200
6/6 [==============================] - 0s 9ms/step - loss: 0.7252 - accuracy: 0.6071
Epoch 11/200
6/6 [========

### Training the ANN on the Training set

In [42]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)


2/2 [==============================] - 0s 9ms/step - loss: 0.7899 - accuracy: 0.5714


[0.7899212837219238, 0.5714285969734192]

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [43]:
y_pred = model.predict(X_test_reshaped)

1/1 [==============================] - 0s 133ms/step


In [44]:
y_pred

array([[0.41733113, 0.00074575, 0.5819232 ],
       [0.41733113, 0.00074575, 0.5819232 ],
       [0.41733113, 0.00074575, 0.5819232 ],
       [0.41733113, 0.00074575, 0.5819232 ],
       [0.34235787, 0.33771637, 0.31992573],
       [0.41733113, 0.00074575, 0.5819232 ],
       [0.34235787, 0.33771634, 0.31992579]], dtype=float32)

In [45]:
y_predRounded= []
y_predEncoded = []


In [46]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [47]:
round(y_pred,y_predRounded)

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predRounded)

0.5714285714285714

In [49]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predRounded, average='micro')

0.5714285714285714