# Artificial Neural Network

### Importing the libraries

In [2]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

In [3]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('ymrs_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[0 1 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [1 1 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 2 0 0]
 [1 0 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 2 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [6]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'N'
 'M' 'D' 'N' 'D' 'M' 'D' 'M' 'N' 'N' 'M' 'D' 'N' 'N' 'N' 'D' 'N' 'D']


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
y= np.array(y.reshape(len(y),1))

In [8]:
print(y)

[['N']
 ['N']
 ['M']
 ['M']
 ['N']
 ['N']
 ['N']
 ['N']
 ['D']
 ['N']
 ['D']
 ['D']
 ['N']
 ['N']
 ['N']
 ['D']
 ['N']
 ['N']
 ['M']
 ['D']
 ['N']
 ['D']
 ['M']
 ['D']
 ['M']
 ['N']
 ['N']
 ['M']
 ['D']
 ['N']
 ['N']
 ['N']
 ['D']
 ['N']
 ['D']]


One Hot Encoding the Y column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [10]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
X_train

array([[0, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 0, 0,

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[-0.2773501   1.60451491  0.          0.         -0.63245553  1.73205081
  -0.19245009  0.          2.44948974  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
   5.19615242  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.

In [15]:
y_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Part 2 - Building the MLP

### Initializing the MLP

In [16]:
clf = MLPClassifier(hidden_layer_sizes=(81,27,9,3),activation="relu",solver='adam', random_state=1)

## Part 3 - Training the MLP

### Training the MLP on the Training set

In [17]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(81, 27, 9, 3), random_state=1)

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [18]:
y_test_pred=clf.predict(X_test)

In [19]:
print(clf.score(X_test, y_test))


0.42857142857142855


In [20]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_pred, average='micro')

0.42857142857142855

In [21]:
y_test_pred

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])