# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [5]:
tf.__version__

'2.8.2'

### Importing the dataset

In [6]:
dataset = pd.read_csv('ymrs_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[0 1 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [1 1 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 2 0 0]
 [1 0 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 2 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [8]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'N'
 'M' 'D' 'N' 'D' 'M' 'D' 'M' 'N' 'N' 'M' 'D' 'N' 'N' 'N' 'D' 'N' 'D']


### Encoding categorical data

In [9]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [11]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[-0.2773501   1.60451491  0.          0.         -0.63245553  1.73205081
  -0.19245009  0.          2.44948974  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
   5.19615242  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.

In [15]:
print(y_train)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [16]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [17]:

ann.add(tf.keras.layers.Dense(units=81, activation='relu'))

### Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=27, activation='relu'))
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))


### Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
6/6 [==============================] - 1s 4ms/step - loss: 1.0543 - accuracy: 0.6071
Epoch 2/200
6/6 [==============================] - 0s 4ms/step - loss: 1.0135 - accuracy: 0.6786
Epoch 3/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9865 - accuracy: 0.6786
Epoch 4/200
6/6 [==============================] - 0s 5ms/step - loss: 0.9578 - accuracy: 0.6071
Epoch 5/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9378 - accuracy: 0.6071
Epoch 6/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9151 - accuracy: 0.6071
Epoch 7/200
6/6 [==============================] - 0s 5ms/step - loss: 0.8978 - accuracy: 0.6071
Epoch 8/200
6/6 [==============================] - 0s 4ms/step - loss: 0.8833 - accuracy: 0.6071
Epoch 9/200
6/6 [==============================] - 0s 4ms/step - loss: 0.8632 - accuracy: 0.6071
Epoch 10/200
6/6 [==============================] - 0s 4ms/step - loss: 0.8459 - accuracy: 0.7143
Epoch 11/200
6/6 [===========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [22]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

In [23]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [24]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])

  

In [25]:
round(ytest_pred,y_test_predRounded)

In [26]:
print(classification_report(y_test_predRounded,y_test))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.67         2
           2       1.00      0.60      0.75         5

   micro avg       0.57      0.57      0.57         7
   macro avg       0.67      0.37      0.47         7
weighted avg       1.00      0.57      0.73         7
 samples avg       0.57      0.57      0.57         7



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.5714285714285714

In [28]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='micro')

0.5714285714285714

In [29]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_predRounded, average='micro')

0.5714285714285714

In [30]:
from sklearn.metrics import precision_score
precision_score(y_test,  y_test_predRounded, average='micro')

0.5714285714285714